# Generated by Django 3.2 on 2022-01-20 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('coupon_type', models.CharField(choices=[('1', 'FLAT'), ('2', 'PERCENTEAGE')], default='1', max_length=32)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
