# Generated by Django 3.2 on 2022-01-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_maximum_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='maximum_discount_amount',
            new_name='maximum_percentage_discount_amount',
        ),
    ]
