# Generated by Django 3.2 on 2022-01-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_coupon_minimum_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_cart_amount',
            field=models.IntegerField(null=True),
        ),
    ]
